library(readr)
AQUACULL <- read_csv("Project/AQUASTAT polished culled.csv")
View(AQUACULL)
hist(AQUACULL$wcOne)


med19 <- median(AQUACULL$wcOne)
med20 <- median(AQUACULL$wcTwo)
med21 <- median(AQUACULL$wcThree)
mean19 <- mean(AQUACULL$wcOne)
mean20 <- mean(AQUACULL$wcTwo)
mean21 <- mean(AQUACULL$wcThree)
var19 <- var(AQUACULL$wcOne)
var20 <- var(AQUACULL$wcTwo)
var21 <- var(AQUACULL$wcThree)
sd19 <- sd(AQUACULL$wcOne)
sd20 <- sd(AQUACULL$wcTwo)
sd21 <- sd(AQUACULL$wcThree)
